(module
  (import "env" "copy_attrset" (func $attrs (param i32 i32 i32) (result i32)))
  (import "env" "copy_attrname" (func $name (param i32 i32 i32 i32)))
  (import "env" "make_attrset" (func $make (param i32 i32) (result i32)))
  (import "env" "get_attr" (func $get (param i32 i32 i32) (result i32)))
  (memory (export "memory") 1)
  (global $leftName i32 (i32.const 12288))
  (global $rightName i32 (i32.const 12292))
  (global $leftLength i32 (i32.const 4))
  (global $rightLength i32 (i32.const 5))
  (data (i32.const 12288) "leftright")
  ;; Separate input descriptors, output descriptors, and name bytes.
  (global $input i32 (i32.const 0))
  (global $output i32 (i32.const 4096))
  (global $strings i32 (i32.const 8192))
  (global $capacity i32 (i32.const 256))
  (global $inputStride i32 (i32.const 8))
  (global $outputStride i32 (i32.const 12))
  (global $lengthOffset i32 (i32.const 4))
  (global $valueOffset i32 (i32.const 8))
  (func (export "nix_wasm_init_v1"))
  (func (export "interleave") (param $pair i32) (result i32)
    (local $left i32) (local $right i32)
    (local.set $left (call $get (local.get $pair) (global.get $leftName) (global.get $leftLength)))
    (local.set $right (call $get (local.get $pair) (global.get $rightName) (global.get $rightLength)))
    (drop (call $roundtrip (local.get $left)))
    (drop (call $roundtrip (local.get $right)))
    (call $roundtrip (local.get $left)))
  (func $roundtrip (export "roundtrip") (param $value i32) (result i32)
    (local $count i32) (local $index i32) (local $src i32)
    (local $dst i32) (local $ptr i32) (local $len i32)
    (local.set $count (call $attrs (local.get $value) (global.get $input) (global.get $capacity)))
    (if (i32.gt_u (local.get $count) (global.get $capacity)) (then unreachable))
    (local.set $ptr (global.get $strings))
    ;; First visit the last index to force a backward reset in the next loop.
    (if (local.get $count) (then
      (local.set $index (i32.sub (local.get $count) (i32.const 1)))
      (local.set $src (i32.add (global.get $input) (i32.mul (local.get $index) (global.get $inputStride))))
      (call $name (local.get $value) (local.get $index) (local.get $ptr)
        (i32.load (i32.add (local.get $src) (global.get $lengthOffset))))))
    (local.set $index (i32.const 0))
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $index) (local.get $count)))
      (local.set $src (i32.add (global.get $input) (i32.mul (local.get $index) (global.get $inputStride))))
      (local.set $dst (i32.add (global.get $output) (i32.mul (local.get $index) (global.get $outputStride))))
      (local.set $len (i32.load (i32.add (local.get $src) (global.get $lengthOffset))))
      (call $name (local.get $value) (local.get $index) (local.get $ptr) (local.get $len))
      ;; Repeated indices must leave the cursor on the same attribute.
      (call $name (local.get $value) (local.get $index) (local.get $ptr) (local.get $len))
      (i32.store (local.get $dst) (local.get $ptr))
      (i32.store (i32.add (local.get $dst) (global.get $lengthOffset)) (local.get $len))
      (i32.store (i32.add (local.get $dst) (global.get $valueOffset)) (i32.load (local.get $src)))
      (local.set $ptr (i32.add (local.get $ptr) (local.get $len)))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br $next)))
    (call $make (global.get $output) (local.get $count))))
