(module
  (import "env" "has_context" (func $has (param i32) (result i32)))
  (import "env" "get_string_context_count" (func $count (param i32) (result i32)))
  (import "env" "make_int" (func $int (param i64) (result i32)))
  (import "env" "make_string_with_context" (func $string (param i32 i32 i32 i32) (result i32)))
  (import "env" "copy_list" (func $copyList (param i32 i32 i32) (result i32)))
  (import "env" "make_list" (func $makeList (param i32 i32) (result i32)))
  (memory (export "memory") 1)
  (global $items i32 (i32.const 128))
  (global $maxItems i32 (i32.const 16))
  (global $itemStride i32 (i32.const 4))
  (global $entries i32 (i32.const 32))
  (global $lengthOffset i32 (i32.const 4))
  (global $badContext i32 (i32.const 64))
  (global $badLength i32 (i32.const 3))
  (data (i32.const 0) "x")
  (data (i32.const 64) "bad")
  (func (export "nix_wasm_init_v1"))
  (func (export "has") (param $value i32) (result i32)
    (call $int (i64.extend_i32_u (call $has (local.get $value)))))
  (func (export "count") (param $value i32) (result i32)
    (call $int (i64.extend_i32_u (call $count (local.get $value)))))
  (func (export "counts") (param $value i32) (result i32)
    (local $length i32) (local $index i32) (local $slot i32) (local $size i32)
    (local.set $length (call $copyList (local.get $value) (global.get $items) (global.get $maxItems)))
    (if (i32.gt_u (local.get $length) (global.get $maxItems)) (then unreachable))
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $index) (local.get $length)))
      (local.set $slot (i32.add (global.get $items) (i32.mul (local.get $index) (global.get $itemStride))))
      (local.set $size (call $count (i32.load (local.get $slot))))
      (if (i32.ne (call $has (i32.load (local.get $slot))) (i32.gt_u (local.get $size) (i32.const 0)))
        (then unreachable))
      (i32.store (local.get $slot) (call $int (i64.extend_i32_u (local.get $size))))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br $next)))
    (call $makeList (global.get $items) (local.get $length)))
  (func (export "invalid") (param i32) (result i32)
    (i32.store (global.get $entries) (global.get $badContext))
    (i32.store (i32.add (global.get $entries) (global.get $lengthOffset)) (global.get $badLength))
    (call $string (i32.const 0) (i32.const 1) (global.get $entries) (i32.const 1))))
